{
    'name' : "Kaushik hoapital system (k)",
    'version' :'1.0',
    'sequence' : 1,
    'website': 'https://www.odoo.com',
    'summary': 'xyz hospital details',
    'description' : "xyz hospital management system",
    'depends' : ['base','contacts','sale_management','purchase'],
    'data' : [
        'security/hospital_security.xml',
        'security/ir.model.access.csv',
        'views/patient.xml',
        'views/doctor.xml',
        'views/nurse.xml',
        'views/ward_boy.xml',
        'views/res_partner_inherit.xml',
        # 'views/product.xml',
        # 'views/dealer.xml',
        # 'views/sale_inherit.xml',
        'views/doctor_report.xml',
        'views/purchase_report.xml',
   ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
}